# Generated by Django 4.2.1 on 2023-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Holiday name')),
                ('holiday_date', models.DateField(verbose_name='holiday date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Holiday description')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created datetime')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated datetime')),
            ],
        ),
    ]
