# Generated by Django 4.2.1 on 2023-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0005_oblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='oblast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.oblast', verbose_name='Oblast'),
        ),
    ]
