# Generated by Django 4.2.1 on 2023-05-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0006_region_oblast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='spravochniki.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='oblast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='spravochniki.oblast', verbose_name='Oblast'),
        ),
    ]
